name: CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:

  sonar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run a sonar scanner
        uses: docker://sonarsource/sonar-scanner-cli:latest
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_URL }}
        with:
          entrypoint: "sonar-scanner"
          args: |
            "-Dproject.settings=./sonar-project.properties"


